#!/usr/bin/env bash
# configure web-02 to be identical to web-01
# The name of the custom HTTP header must be served by X-Served-By

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chmod -R 755 /var/www
sudo echo 'Hello World' > /var/www/html/index.html
sudo echo "Ceci n'est pas une page" > /var/www/html/404.html
server_config=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        add_header X-Served-By \$hostname;
        location / {
                try_files \$uri \$uri/ =404;
        }
        error_page 404 /404.html;
        location  /404.html {
            internal;
        }

        if (\$request_filename ~ redirect_me){
            rewrite ^ https://www.linkedin.com permanent;
        }
}
"

sudo echo "$server_config" > /etc/nginx/sites-available/default
sudo service nginx start

